source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'ContentPreviewVPS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContentPreviewVPS
pod 'VPSNMobile', :path => '../..'
end
